# Generated by Django 2.2.7 on 2019-11-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(help_text='Activar o Desactivar Hydra', verbose_name='Activo')),
            ],
        ),
    ]
