# Generated by Django 2.2.7 on 2019-11-07 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='ambient_alert',
            field=models.BooleanField(default=True, help_text='Alerta de Humedad Ambiental', verbose_name='Alerta de Humedad Ambiental'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='humidity_alert',
            field=models.BooleanField(default=True, help_text='Alerta de Humedad', verbose_name='Alerta de Humedad'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='light_alert',
            field=models.BooleanField(default=True, help_text='Alerta de Luz', verbose_name='Alerta de Luz'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='movement_alert',
            field=models.BooleanField(default=True, help_text='Alerta de Movimiento', verbose_name='Alerta de Movimiento'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='post_instagram',
            field=models.BooleanField(default=True, help_text='Postear en Instagram', verbose_name='Postear en Instagram'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='post_telegram',
            field=models.BooleanField(default=True, help_text='Postear en Telegram', verbose_name='Postear en Telegram'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='post_twitter',
            field=models.BooleanField(default=True, help_text='Postear en Twitter', verbose_name='Postear en Twitter'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='temperature_alert',
            field=models.BooleanField(default=True, help_text='Alerta de Temperatura', verbose_name='Alerta de Temperatura'),
        ),
    ]
