# Generated by Django 2.0.1 on 2019-11-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_auto_20191106_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.PositiveSmallIntegerField(verbose_name='Temperatura')),
                ('humidity', models.PositiveSmallIntegerField(verbose_name='Temperatura')),
                ('light', models.PositiveSmallIntegerField(verbose_name='Temperatura')),
                ('mov', models.PositiveSmallIntegerField(verbose_name='Temperatura')),
                ('ambient', models.PositiveSmallIntegerField(verbose_name='Temperatura')),
            ],
        ),
        migrations.AlterField(
            model_name='configuration',
            name='post_instagram',
            field=models.BooleanField(default=True, help_text='Comunicación con Instagram', verbose_name='Comunicación con Instagram'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='post_telegram',
            field=models.BooleanField(default=True, help_text='Comunicación con Telegram', verbose_name='Comunicación con Telegram'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='post_twitter',
            field=models.BooleanField(default=True, help_text='Comunicación con Twitter', verbose_name='Comunicación con Twitter'),
        ),
    ]
